<?php
require_once($_SERVER['DOCUMENT_ROOT'] . '/webEdition/we/include/weTagWizard/classes/weTagData_selectAttribute.class.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/webEdition/we/include/weTagWizard/classes/weTagData_choiceAttribute.class.php');

$GLOBALS['weTagWizard']['weTagData']['needsEndtag'] = false;

$GLOBALS['weTagWizard']['attribute']['id706_name'] = new weTagData_selectAttribute('706', 'name', array(new weTagDataOption('name', false, ''), new weTagDataOption('display', false, ''), new weTagDataOption('text', false, ''), new weTagDataOption('href', false, ''), new weTagDataOption('icon', false, ''), new weTagDataOption('position', false, ''), new weTagDataOption('level', false, ''), new weTagDataOption('current', false, ''), new weTagDataOption('id', false, ''), new weTagDataOption('parentid', false, ''), new weTagDataOption('title', false, ''), new weTagDataOption('anchor', false, ''), new weTagDataOption('target', false, ''), new weTagDataOption('lang', false, ''), new weTagDataOption('hreflang', false, ''), new weTagDataOption('accesskey', false, ''), new weTagDataOption('tabindex', false, ''), new weTagDataOption('rel', false, ''), new weTagDataOption('rev', false, ''), new weTagDataOption('properties', false, ''), new weTagDataOption('icon_width', false, ''), new weTagDataOption('icon_height', false, ''), new weTagDataOption('icon_border', false, ''), new weTagDataOption('icon_hspace', false, ''), new weTagDataOption('icon_vspace', false, ''), new weTagDataOption('icon_align', false, ''), new weTagDataOption('icon_alt', false, ''), new weTagDataOption('icon_title', false, ''), new weTagDataOption('popup_open', false, ''), new weTagDataOption('popup_center', false, ''), new weTagDataOption('popup_xposition', false, ''), new weTagDataOption('popup_yposition', false, ''), new weTagDataOption('popup_width', false, ''), new weTagDataOption('popup_height', false, ''), new weTagDataOption('popup_toolbar', false, ''), new weTagDataOption('popup_status', false, ''), new weTagDataOption('popup_scrollbars', false, ''), new weTagDataOption('popup_menubar', false, ''), new weTagDataOption('popup_resizable', false, ''), new weTagDataOption('popup_location', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id724_attributes'] = new weTagData_choiceAttribute('724', 'attributes', array(new weTagDataOption('position', false, ''), new weTagDataOption('rel', false, ''), new weTagDataOption('tabindex', false, ''), new weTagDataOption('accesskey', false, ''), new weTagDataOption('hreflang', false, ''), new weTagDataOption('lang', false, ''), new weTagDataOption('target', false, ''), new weTagDataOption('anchor', false, ''), new weTagDataOption('title', false, ''), new weTagDataOption('current', false, ''), new weTagDataOption('level', false, ''), new weTagDataOption('link', false, ''), new weTagDataOption('image', false, ''), new weTagDataOption('text', false, ''), new weTagDataOption('href', false, ''), new weTagDataOption('icon', false, ''), new weTagDataOption('rev', false, '')), false,true, '');
$GLOBALS['weTagWizard']['attribute']['id726_complete'] = new weTagData_selectAttribute('726', 'complete', array(new weTagDataOption('link', false, ''), new weTagDataOption('image', false, '')), false, '');
?>