<?php
require_once($_SERVER['DOCUMENT_ROOT'] . '/webEdition/we/include/weTagWizard/classes/weTagData_textAttribute.class.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/webEdition/we/include/weTagWizard/classes/weTagData_selectAttribute.class.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/webEdition/we/include/weTagWizard/classes/weTagData_typeAttribute.class.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/webEdition/we/include/weTagWizard/classes/weTagData_choiceAttribute.class.php');

$GLOBALS['weTagWizard']['weTagData']['needsEndtag'] = false;

$GLOBALS['weTagWizard']['attribute']['id517_name'] = new weTagData_textAttribute('517', 'name', true, '');
$GLOBALS['weTagWizard']['attribute']['id518_cols'] = new weTagData_textAttribute('518', 'cols', false, '');
$GLOBALS['weTagWizard']['attribute']['id519_rows'] = new weTagData_textAttribute('519', 'rows', false, '');
$GLOBALS['weTagWizard']['attribute']['id520_autobr'] = new weTagData_selectAttribute('520', 'autobr', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id521_importrtf'] = new weTagData_selectAttribute('521', 'importrtf', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id522_width'] = new weTagData_textAttribute('522', 'width', false, '');
$GLOBALS['weTagWizard']['attribute']['id523_height'] = new weTagData_textAttribute('523', 'height', false, '');
$GLOBALS['weTagWizard']['attribute']['id524_bgcolor'] = new weTagData_textAttribute('524', 'bgcolor', false, '');
$GLOBALS['weTagWizard']['attribute']['id525_html'] = new weTagData_selectAttribute('525', 'html', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id526_htmlspecialchars'] = new weTagData_selectAttribute('526', 'htmlspecialchars', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id527_php'] = new weTagData_selectAttribute('527', 'php', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id528_wysiwyg'] = new weTagData_typeAttribute('528', 'wysiwyg', array(new weTagDataOption('true', false, '', array('id528_wysiwyg','id517_name','id518_cols','id519_rows','id520_autobr','id521_importrtf','id522_width','id523_height','id524_bgcolor','id525_html','id526_htmlspecialchars','id527_php','id529_commands','id530_fontnames','id532_abbr','id533_removefirstparagraph','id534_inlineedit','id535_buttonpos','id536_win2iso','id537_classes','id732_spellcheck'), array('id517_name')), new weTagDataOption('false', false, '', array('id528_wysiwyg','id517_name','id518_cols','id519_rows','id520_autobr','id525_html','id526_htmlspecialchars','id527_php','id532_abbr','id732_spellcheck'), array('id517_name'))), false, '');
$GLOBALS['weTagWizard']['attribute']['id529_commands'] = new weTagData_choiceAttribute('529', 'commands', array(new weTagDataOption('acronym', false, ''), new weTagDataOption('anchor', false, ''), new weTagDataOption('applystyle', false, ''), new weTagDataOption('backcolor', false, ''), new weTagDataOption('bold', false, ''), new weTagDataOption('caption', false, ''), new weTagDataOption('color', false, ''), new weTagDataOption('copy', false, ''), new weTagDataOption('copypaste', false, ''), new weTagDataOption('createlink', false, ''), new weTagDataOption('cut', false, ''), new weTagDataOption('decreasecolspan', false, ''), new weTagDataOption('deletecol', false, ''), new weTagDataOption('deleterow', false, ''), new weTagDataOption('editcell', false, ''), new weTagDataOption('editsource', false, ''), new weTagDataOption('edittable', false, ''), new weTagDataOption('fontname', false, ''), new weTagDataOption('fontsize', false, ''), new weTagDataOption('forecolor', false, ''), new weTagDataOption('formatblock', false, ''), new weTagDataOption('fullscreen', false, ''), new weTagDataOption('importrtf', false, ''), new weTagDataOption('increasecolspan', false, ''), new weTagDataOption('indent', false, ''), new weTagDataOption('insertbreak', false, ''), new weTagDataOption('insertcolumnleft', false, ''), new weTagDataOption('insertcolumnright', false, ''), new weTagDataOption('inserthorizontalrule', false, ''), new weTagDataOption('insertimage', false, ''), new weTagDataOption('insertorderedlist', false, ''), new weTagDataOption('insertrowabove', false, ''), new weTagDataOption('insertrowbelow', false, ''), new weTagDataOption('insertspecialchar', false, ''), new weTagDataOption('inserttable', false, ''), new weTagDataOption('insertunorderedlist', false, ''), new weTagDataOption('italic', false, ''), new weTagDataOption('justify', false, ''), new weTagDataOption('justifycenter', false, ''), new weTagDataOption('justifyfull', false, ''), new weTagDataOption('justifyleft', false, ''), new weTagDataOption('justifyright', false, ''), new weTagDataOption('lang', false, ''), new weTagDataOption('link', false, ''), new weTagDataOption('list', false, ''), new weTagDataOption('outdent', false, ''), new weTagDataOption('paste', false, ''), new weTagDataOption('prop', false, ''), new weTagDataOption('redo', false, ''), new weTagDataOption('removecaption', false, ''), new weTagDataOption('removeformat', false, ''), new weTagDataOption('spellcheck', false, ''), new weTagDataOption('strikethrough', false, ''), new weTagDataOption('subscript', false, ''), new weTagDataOption('superscript', false, ''), new weTagDataOption('underline', false, ''), new weTagDataOption('table', false, ''), new weTagDataOption('undo', false, ''), new weTagDataOption('unlink', false, ''), new weTagDataOption('visibleborders', false, '')), false,true, '');
$GLOBALS['weTagWizard']['attribute']['id530_fontnames'] = new weTagData_choiceAttribute('530', 'fontnames', array(new weTagDataOption('arial', false, ''), new weTagDataOption('courier', false, ''), new weTagDataOption('tahoma', false, ''), new weTagDataOption('times', false, ''), new weTagDataOption('verdana', false, ''), new weTagDataOption('wingdings', false, '')), false,true, '');
$GLOBALS['weTagWizard']['attribute']['id628_xml'] = new weTagData_selectAttribute('628', 'xml', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id532_abbr'] = new weTagData_selectAttribute('532', 'abbr', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id533_removefirstparagraph'] = new weTagData_selectAttribute('533', 'removefirstparagraph', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id534_inlineedit'] = new weTagData_selectAttribute('534', 'inlineedit', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id535_buttonpos'] = new weTagData_choiceAttribute('535', 'buttonpos', array(new weTagDataOption('top', false, ''), new weTagDataOption('bottom', false, '')), false,false, '');
$GLOBALS['weTagWizard']['attribute']['id536_win2iso'] = new weTagData_selectAttribute('536', 'win2iso', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, '');
$GLOBALS['weTagWizard']['attribute']['id537_classes'] = new weTagData_textAttribute('537', 'classes', false, '');
$GLOBALS['weTagWizard']['attribute']['id732_spellcheck'] = new weTagData_selectAttribute('732', 'spellcheck', array(new weTagDataOption('true', false, ''), new weTagDataOption('false', false, '')), false, 'spellchecker');
$GLOBALS['weTagWizard']['attribute']['id734_cachelifetime'] = new weTagData_textAttribute('734', 'cachelifetime', false, '');
?>